1) Convert a series of date-strings to a timeseries?

In [3]:
import pandas as pd

dates = ['2025-01-01', '2025-01-02', '2025-01-03']
series = pd.to_datetime(dates)

print(series)
print(type(series))

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

2. Create two DataFrames, df1 and df2, with a common column (e.g., 'ID'). 

-Perform an inner merge on this common column and display the resulting DataFrame.<br>
-Perform a left join of df1 and df2 on the 'ID' column. Explain how missing values are handled in the resulting DataFrame. 
 Right Join and Index-Based Join.<br>
-Perform a right join using pd.merge() on a common column, then perform a join using df.join() based on the index. Compare the results. Merging with Multiple Keys.

In [11]:
df1 = pd.DataFrame({
    'id': [1, 2, 3, 4, 6],
    'name': ['A1', 'A2', 'A3', 'A4', 'A6'],
    'sub': ['sub1', 'sub2', 'sub3', 'sub4', 'sub6']
})

df2 = pd.DataFrame({
    'id': [2, 1, 3, 4, 5],
    'name': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'sub': ['sub1', 'sub2', 'sub3', 'sub4', 'sub5']
})

print("DF1:")
print(df1)

print("\nDF2:")
print(df2)

DF1:
   id name   sub
0   1   A1  sub1
1   2   A2  sub2
2   3   A3  sub3
3   4   A4  sub4
4   6   A6  sub6

DF2:
   id name   sub
0   2   B1  sub1
1   1   B2  sub2
2   3   B3  sub3
3   4   B4  sub4
4   5   B5  sub5

In [14]:
#inner_merge
pd.merge(df1, df2, on='id', how='inner')

   id name_x sub_x name_y sub_y
0   1     A1  sub1     B2  sub2
1   2     A2  sub2     B1  sub1
2   3     A3  sub3     B3  sub3
3   4     A4  sub4     B4  sub4

In [ ]:
#left_merge
pd.merge(df1, df2, on='id', how='left')

#Missing Values Handling
#All rows from df1 are kept.
#If a matching ID is not found in df2, Pandas fills the value with NaN.

   id name_x sub_x name_y sub_y
0   1     A1  sub1     B2  sub2
1   2     A2  sub2     B1  sub1
2   3     A3  sub3     B3  sub3
3   4     A4  sub4     B4  sub4
4   6     A6  sub6    NaN   NaN

In [16]:
#right_merge
pd.merge(df1, df2, on='id', how='right')

   id name_x sub_x name_y sub_y
0   2     A2  sub2     B1  sub1
1   1     A1  sub1     B2  sub2
2   3     A3  sub3     B3  sub3
3   4     A4  sub4     B4  sub4
4   5    NaN   NaN     B5  sub5

In [30]:
#Join operation
df1_index.join(df2_index, lsuffix='_left', rsuffix='_right')

   name_left sub_left name_right sub_right
id
1         A1     sub1         B2      sub2
2         A2     sub2         B1      sub1
3         A3     sub3         B3      sub3
4         A4     sub4         B4      sub4
6         A6     sub6        NaN       NaN

In [20]:
#Merging with Multiple Keys
pd.merge(df1, df2, on=['id', 'sub'])

   id name_x   sub name_y
0   3     A3  sub3     B3
1   4     A4  sub4     B4

3) Create three DataFrames. Vertically concatenate two of them using pd.concat(), then merge the resulting DataFrame with the third DataFrame on a common key. T Understand join() vs. merge().

Also Explain the primary differences between df.join() and pd.merge(),

In [21]:
dfA = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Aman', 'Riya']
})

dfB = pd.DataFrame({
    'ID': [3, 4],
    'Name': ['Karan', 'Neha']
})

dfC = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'City': ['Jaipur', 'Delhi', 'Mumbai', 'Pune']
})

print(dfA)
print('='*20)
print(dfB)
print('='*20)
print(dfC)

   ID  Name
0   1  Aman
1   2  Riya
====================
   ID   Name
0   3  Karan
1   4   Neha
====================
   ID    City
0   1  Jaipur
1   2   Delhi
2   3  Mumbai
3   4    Pune

In [22]:
vertical = pd.concat([dfA, dfB], axis=0)
vertical

   ID   Name
0   1   Aman
1   2   Riya
0   3  Karan
1   4   Neha

In [31]:
final = pd.merge(vertical, dfC, on='ID')
final

   ID   Name    City
0   1   Aman  Jaipur
1   2   Riya   Delhi
2   3  Karan  Mumbai
3   4   Neha    Pune

### Difference Between `join()` and `merge()`

| `df.join()` | `pd.merge()` |
|---|---|
| Joins mainly on index | Joins on columns or index |
| Simpler syntax | More powerful and flexible |
| Default join is left | Default join is inner |
| Best for index-based operations | Best for SQL-style operations |
| Used with DataFrames | Can merge Series and DataFrames |